BEGIN;

CREATE TABLE IF NOT EXISTS public.evaluation_parcours_therapeutique (
    id_parcours BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluation INT NOT NULL,
    angiocholite BOOLEAN,
    tumeur_controlee BOOLEAN,
    nouvelles_metastases BOOLEAN,
    chirurgie_d_emblee BOOLEAN,
    traitement_medical_prevu BOOLEAN,
    pas_de_progression_apres_16_semaines_platine BOOLEAN,
    date_reevaluation DATE,
    commentaire TEXT,
    date_creation TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_parcours_evaluation FOREIGN KEY (id_evaluation)
        REFERENCES public.evaluation_clinique(id_evaluation) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_parcours_evaluation_date
    ON public.evaluation_parcours_therapeutique (id_evaluation, date_reevaluation DESC, id_parcours DESC);

COMMIT;
